# Site settings
title: Surviving Knowledge
header-img: img/home-bg.png
email: ezirens@gmail.com
copyright_name: survivingknowledge
description: > # this means to ignore newlines until "baseurl:"
  Coding adventures for the non-sane
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  survivingknowledge
learn_profile: survivingknowledge
email_username: ezirens@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
